We should check UTF-8 bit distribution in copyMultibyteCharData. If use data is erroneous e.g. outside the range 0x80 first byte we will eat the four characters, this will cause the right end bracket to be eaten and the erroneous message and a trace dump like: <!DOCTYPE doc [ <!ELEMENT doc (#PCDATA)> ]> <doc>�</doc>
I get the following error:


[Fatal Error] test.xml:5:1: The element type "doc" must be terminated by the
matching end-tag "</doc>".
org.xml.sax.SAXException: Stopping after fatal error: The element type "doc"
must be terminated by the matching end-tag "</doc>".
        at java.lang.Throwable.fillInStackTrace(Native Method)
        at java.lang.Throwable.fillInStackTrace(Compiled Code)
        at java.lang.Throwable.<init>(Compiled Code)
        at java.lang.Exception.<init>(Exception.java:42)
        at org.xml.sax.SAXException.<init>(SAXException.java:45)
        at
org.apache.xerces.framework.XMLParser.reportError(XMLParser.java:1001)
        at
org.apache.xerces.framework.XMLDocumentScanner.reportFatalXMLError(XMLDocumentSc
anner.java:634)
        at
org.apache.xerces.framework.XMLDocumentScanner$ContentDispatcher.endOfInput(XMLD
ocumentScanner.java:1457)
        at
org.apache.xerces.framework.XMLDocumentScanner.endOfInput(XMLDocumentScanner.jav
a:417)
        at
org.apache.xerces.validators.common.XMLValidator.sendEndOfInputNotifications(XML
Validator.java:448)
        at
org.apache.xerces.readers.DefaultEntityHandler.changeReaders(DefaultEntityHandle
r.java:1006)
        at
org.apache.xerces.readers.XMLEntityReader.changeReaders(XMLEntityReader.java:168
)
        at
org.apache.xerces.readers.UTF8Reader.changeReaders(UTF8Reader.java:182)
        at org.apache.xerces.readers.UTF8Reader.scanContent(Compiled Code)
        at
org.apache.xerces.framework.XMLDocumentScanner$ContentDispatcher.dispatch(Compil
ed Code)
        at org.apache.xerces.framework.XMLDocumentScanner.parseSome(Compiled
Code)
        at org.apache.xerces.framework.XMLParser.parse(XMLParser.java:861)
        at org.apache.xerces.framework.XMLParser.parse(XMLParser.java:900)
        at sax.SAXCount.print(SAXCount.java:152)
        at sax.SAXCount.main(Compiled Code)

This should not be the case and we should return the real error:

[Fatal Error] bugp.xml:4:7: An invalid XML character (Unicode: 0xa3) was found i
n the element content of the document.
org.xml.sax.SAXException: Stopping after fatal error: An invalid XML character (
Unicode: 0xa3) was found in the element content of the document.
        at java.lang.Throwable.<init>(Throwable.java:96)
        at java.lang.Exception.<init>(Exception.java:44)
        at org.xml.sax.SAXException.<init>(SAXException.java:45)
        at org.apache.xerces.framework.XMLParser.reportError(XMLParser.java:1001
)
        at org.apache.xerces.framework.XMLDocumentScanner.reportFatalXMLError(XM
LDocumentScanner.java:643)
        at org.apache.xerces.framework.XMLDocumentScanner$ContentDispatcher.disp
atch(XMLDocumentScanner.java:1390)
        at org.apache.xerces.framework.XMLDocumentScanner.parseSome(XMLDocumentS
canner.java:380)
        at org.apache.xerces.framework.XMLParser.parse(XMLParser.java:861)
        at org.apache.xerces.framework.XMLParser.parse(XMLParser.java:900)
        at sax.SAXCount.print(SAXCount.java:152)
        at sax.SAXCount.main(SAXCount.java:372)





PR:
Obtained from:
Submitted by:
Reviewed by:


git-svn-id: https://svn.apache.org/repos/asf/xerces/java/trunk@315970 13f79535-47bb-0310-9956-ffa450edef68