Fix to some error-reporting vis. entity refs lacking their semicolon. Now we get error messages like
[Fatal Error] distribution-process.txt:14:9: The reference to entity "aposll" must end with the ';' delimiter.
error: Parse error occurred - The reference to entity "aposll" must end with the ';' delimiter.

instead of ones like

[Fatal Error] distribution-process.txt:14:9: The reference to entity "{0}" must end with the '';'' delimiter.
error: Parse error occurred - The reference to entity "{0}" must end with the '';'' delimiter.


git-svn-id: https://svn.apache.org/repos/asf/xerces/java/trunk@317726 13f79535-47bb-0310-9956-ffa450edef68