Update the BaseMarkupSerializer in order to not be strictly dependent on DOM Level 2. When the serializer queries the system and public IDs on the DocumentType, I catch the NoSuchMethodError so that reflection can be used if the DOM implementation is not DOM Level 2 compliant.
This is a better fix than calling DOMImplementation#hasFeature because
if the DOM implementation is written to DOM Level 2 but DOM Level 1
interfaces are present in the classpath before the DOM Level 2
interfaces, then the VM will load the older interfaces and throw a
NoSuchMethodError.
PR: 66


git-svn-id: https://svn.apache.org/repos/asf/xerces/java/trunk@315375 13f79535-47bb-0310-9956-ffa450edef68